version: '3.8'
services:
  web:
    build: ./image_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./image_project/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:latest
  celery:
    build: ./image_project
    command: celery -A image_project worker -l INFO
    volumes:
      - ./image_project/:/usr/src/app/
    depends_on:
      - redis
  celery_beat:
    build: ./image_project
    command: celery -A image_project beat -l INFO
    volumes:
      - ./image_project/:/usr/src/app/
    depends_on:
      - redis
  flower:
    image: flower
    build: ./image_project
    command: celery -A image_project --broker=redis://redis:6379 flower
    volumes:
      - ./image_project/:/usr/src/app/
    ports:
      - 5555:5555
    depends_on:
      - redis
      - web
      - celery
